// insert_lots3_12.js
(function() {
  const request = indexedDB.open("NotlyDB", 2);

  request.onsuccess = function(event) {
    const db = event.target.result;
    console.log("Connexion à NotlyDB réussie pour insertion lots 3 à 12");

const produits = [
  // Lot 3 : Kits couture
  { nom: "Machine à coudre (vêtements) - Tête blanche simple (mécanique)", categorieId: 3 },
  { nom: "Machine à coudre (vêtements) - Tête noire simple (mécanique)", categorieId: 3 },
  { nom: "Machine à coudre (vêtements) - Tête blanche électrique", categorieId: 3 },
  { nom: "Machine à coudre (vêtements) - Tête blanche électrique", categorieId: 3 },
  { nom: "Ciseaux grand format - 6 pouces", categorieId: 3 },
  { nom: "Boîte à punaises - Métal (boite de 480/500)", categorieId: 3 },
  { nom: "Aiguille pour machine - Dozen", categorieId: 3 },
  { nom: "Aiguille à mains - Taille 2", categorieId: 3 },
  { nom: "Mètre ruban de 2 m - En plastique", categorieId: 3 },
  { nom: "Grand fer à repasser - Electrique (1200 à 1500 WATT)", categorieId: 3 },
  { nom: "Grand fer à repasser - Charbon", categorieId: 3 },
  { nom: "Huile pour machine - 1L", categorieId: 3 },
  { nom: "Mannequin en plastique - Pour étaler les habits", categorieId: 3 },
  { nom: "Cannettes - En coton", categorieId: 3 },
  { nom: "Navettes - Pièce contenant le fil de la machine à coudre", categorieId: 3 },
  { nom: "Rouleau de fil à coudre - Paquet", categorieId: 3 },
  { nom: "Boutons d'habit - Paquet", categorieId: 3 },
  { nom: "Fermetures éclaires homme - Longueur 12 à 20 cm", categorieId: 3 },
  { nom: "Fermetures éclaires femme - Longueur ≥ 50 cm", categorieId: 3 },
  { nom: "Popeline noir et blanc - 1m", categorieId: 3 },
  { nom: "Tissu en coton - 1m", categorieId: 3 },
  { nom: "Pagne en coton - 1 Pièce de 3", categorieId: 3 },


      // Lot 4 : Menuiserie
  { nom: "Kit menuiserie complet", categorieId: 4 },
  { nom: "Table en bois - L=200cm / l=80cm / H=100cm", categorieId: 4 },
  { nom: "Table en planche - L=90cm / l=50cm / H=60cm", categorieId: 4 },
  { nom: "Table en planche - L=100cm / l=60cm / H=60cm", categorieId: 4 },
  { nom: "Banc en bois - L=200cm / l=30cm / H=40cm", categorieId: 4 },
  { nom: "Table en planche - L=200cm / l=100cm / H=100cm", categorieId: 4 },
  { nom: "Tabouret de cuisine - En bois blancs", categorieId: 4 },

      // Lot 5 : Saponification
  { nom: "Kit saponification complet", categorieId: 5 },
  { nom: "Gants de ménage latex - Gant rouge très résistant pour fabrication de savon", categorieId: 5 },
  { nom: "Panier de course en plastique (tissé) - 20 à 30 L", categorieId: 5 },
  { nom: "Chaussures de sécurité - Paire (différentes tailles)", categorieId: 5 },
  { nom: "Soude caustique - Sac de 25 kg", categorieId: 5 },
  { nom: "Silicate de sodium - Flacon de 500 ml", categorieId: 5 },
  { nom: "Parfum - Flacon de 10 ml", categorieId: 5 },
  { nom: "Neutralisant - Flacon de 1 L", categorieId: 5 },
  { nom: "Beurre de karité - Pot de 1 kg", categorieId: 5 },
  { nom: "Huile de coco - Flacon de 60 ml", categorieId: 5 },
  { nom: "Huile de palmiste - Flacon de 1 L", categorieId: 5 },
  { nom: "Carbonate de sodium - Pot de 4 kg", categorieId: 5 },

      // Lot 6 : Kits produit alimentaire (FOOD)
  { nom: "Kit alimentaire complet", categorieId: 6 },
  { nom: "Maïs - 1kg", categorieId: 6 },
  { nom: "Maïs - Sac de 50 kg", categorieId: 6 },
  { nom: "Maïs - Sac de 100 kg", categorieId: 6 },
  { nom: "Sorgho blanc - 1kg", categorieId: 6 },
  { nom: "Sorgho blanc - Sac de 50 kg", categorieId: 6 },
  { nom: "Sorgho blanc - Sac de 100 kg", categorieId: 6 },
  { nom: "Niébé blanc - 1kg", categorieId: 6 },
  { nom: "Niébé blanc - Sac de 50 kg", categorieId: 6 },
  { nom: "Niébé blanc - Sac de 100 kg", categorieId: 6 },
  { nom: "Niébé rouge - 1kg", categorieId: 6 },
  { nom: "Niébé rouge - Sac de 50 kg", categorieId: 6 },
  { nom: "Niébé rouge - Sac de 100 kg", categorieId: 6 },
  { nom: "Riz local - 1kg", categorieId: 6 },
  { nom: "Riz local - Sac de 50 kg", categorieId: 6 },
  { nom: "Riz local - Sac de 100 kg", categorieId: 6 },
  { nom: "Riz importé - 1kg", categorieId: 6 },
  { nom: "Riz importé - Sac de 50 kg", categorieId: 6 },
  { nom: "Riz importé - Sac de 100 kg", categorieId: 6 },
  { nom: "Petit mil - 1kg", categorieId: 6 },
  { nom: "Petit mil - Sac de 50 kg", categorieId: 6 },
  { nom: "Petit mil - Sac de 100 kg", categorieId: 6 },
  { nom: "Maggie Bouillon (cube, poulet) - Paquet", categorieId: 6 },
  { nom: "Maggie Bouillon (cube, jumbo) - Paquet", categorieId: 6 },
  { nom: "Maggie Bouillon (cube, tablette) - Paquet", categorieId: 6 },
  { nom: "Oignons - Sac de 25 kg", categorieId: 6 },
  { nom: "Oignons - Sac de 50 kg", categorieId: 6 },
  { nom: "Feuille d'oignons sèchés - Sac de 25 kg", categorieId: 6 },
  { nom: "Feuille d'oignons sèchés - Sac de 50 kg", categorieId: 6 },
  { nom: "Bonbon bâton Rio-pop - Paquet", categorieId: 6 },
  { nom: "Bonbon au lait RAMA - Carton", categorieId: 6 },
  { nom: "Pâte alimentaire (Spaghetti) - Paquet de 250g", categorieId: 6 },
  { nom: "Pâte alimentaire (Spaghetti) - Carton de paquet de 250g", categorieId: 6 },
  { nom: "Pâte alimentaire (Macaroni) - Carton de paquet de 200g", categorieId: 6 },
  { nom: "Pâte alimentaire (Macaroni) - Paquet de 200g", categorieId: 6 },
  { nom: "Sucre en poudre - 1kg", categorieId: 6 },
  { nom: "Sucre en poudre - Sac de 25 kg", categorieId: 6 },
  { nom: "Sucre en poudre - Sac de 50 kg", categorieId: 6 },
  { nom: "Sucre en carreau - Paquet de 1kg", categorieId: 6 },
  { nom: "Lait en poudre - Cawbell ou Nido sachet de 1kg", categorieId: 6 },
  { nom: "Thé Achoura - Cartouche de 10 paquets", categorieId: 6 },
  { nom: "Thé Cana - Cartouche de 10 paquets", categorieId: 6 },
  { nom: "Lait en poudre - Cawbell ou équivalent sac de 50kg", categorieId: 6 },
  { nom: "Sel granulé - 1kg", categorieId: 6 },
  { nom: "Sel granulé - Sac de 25 kg", categorieId: 6 },
  { nom: "Biscuit Parle G ou Mona G - Paquet", categorieId: 6 },
  { nom: "Thé vert de Chine lot de 10 - Paquet", categorieId: 6 },
  { nom: "Poisson sec - 1kg", categorieId: 6 },
  { nom: "Kapokier - 1kg", categorieId: 6 },
  { nom: "Gombo sec - 1kg", categorieId: 6 },
  { nom: "Gombo sec - Sac de 50 kg", categorieId: 6 },
  { nom: "Gombo sec - Sac de 100 kg", categorieId: 6 },
  { nom: "Soumbala (grosse boule) - 1kg", categorieId: 6 },
  { nom: "Piment (petit piment) sec - 1kg", categorieId: 6 },
  { nom: "Piment (petit piment) sec - Sac de 50 kg", categorieId: 6 },
  { nom: "Piment (petit piment) sec - Sac de 100 kg", categorieId: 6 },
  { nom: "Piment frais - 1kg", categorieId: 6 },
  { nom: "Piment frais - Sac de 50 kg", categorieId: 6 },
  { nom: "Piment frais - Sac de 100 kg", categorieId: 6 },
  { nom: "Ail - 1kg", categorieId: 6 },
  { nom: "Pâte d'arachide - 1kg", categorieId: 6 },
  { nom: "Pâte d'arachide - Seau de 20kg", categorieId: 6 },
  { nom: "Feuille de baobab sèche - 1kg", categorieId: 6 },
  { nom: "Feuille de baobab sèche - Sac de 50 kg", categorieId: 6 },
  { nom: "Feuille de baobab sèche - Sac de 100 kg", categorieId: 6 },
  { nom: "Arachide décortiqué - 1kg", categorieId: 6 },
  { nom: "Arachide décortiqué - Sac de 50 kg", categorieId: 6 },
  { nom: "Arachide décortiqué - Sac de 100 kg", categorieId: 6 },
  { nom: "Farine de blé - Sac de 50 kg", categorieId: 6 },
  { nom: "Levure industrielle - Carton de 36 sachets", categorieId: 6 },
  { nom: "Levure industrielle - Paquet", categorieId: 6 },
  { nom: "Levure industrielle - Sachet", categorieId: 6 },
  { nom: "Arôme - Carton", categorieId: 6 },
  { nom: "Bissap - 1kg", categorieId: 6 },
  { nom: "Bissap - Sac de 50 kg", categorieId: 6 },
  { nom: "Bissap - Sac de 100 kg", categorieId: 6 },
  { nom: "Gingembre - 1kg", categorieId: 6 },
  { nom: "Gingembre - Sac de 50 kg", categorieId: 6 },
  { nom: "Gingembre - Sac de 100 kg", categorieId: 6 },
  { nom: "Noix de néré - 1kg", categorieId: 6 },
  { nom: "Noix de néré - Sac de 50 kg", categorieId: 6 },
  { nom: "Noix de néré - Sac de 100 kg", categorieId: 6 },
  { nom: "Pâte de tomate GILDAS ou équivalent - 2,2kg", categorieId: 6 },
  { nom: "Huile alimentaire DINOR ou équivalent - Bidon de 20L", categorieId: 6 },
  { nom: "Huile alimentaire DINOR ou équivalent - Bidon de 25L", categorieId: 6 },
  { nom: "Huile alimentaire SAVOR ou équivalent - Bidon de 20L", categorieId: 6 },
  { nom: "Huile alimentaire SAVOR ou équivalent - Bidon de 25L", categorieId: 6 },
  { nom: "Tamarin - 1kg", categorieId: 6 },
  { nom: "Tamarin - Sac de 50 kg", categorieId: 6 },
  { nom: "Tamarin - Sac de 100 kg", categorieId: 6 },

      // Lot 7 : Équipement Maraîchage
      { nom: "Équipement maraîchage complet", categorieId: 7 },
{ nom: "Binette - Trois fourches de type industrielle", categorieId: 7 },
{ nom: "Binette - deux fourches de type industrielle", categorieId: 7 },
{ nom: "Arrosoir - En plastique 12L", categorieId: 7 },
{ nom: "Machette - Type industrielle", categorieId: 7 },
{ nom: "Houe - Industrielle au format moyen", categorieId: 7 },
{ nom: "Daba - Type industrielle", categorieId: 7 },
{ nom: "Râteau + manche en bois - Type industrielle", categorieId: 7 },
{ nom: "Pelle + manche en bois - Type industrielle", categorieId: 7 },
{ nom: "Pioche + manche en bois - Type industrielle", categorieId: 7 },
{ nom: "Fourche + manche - Type industrielle", categorieId: 7 },
{ nom: "Engrais Urée de 50kg - 50kg", categorieId: 7 },
{ nom: "Engrais NPK 50kg - 50kg", categorieId: 7 },
{ nom: "Bottes - En plastique", categorieId: 7 },
{ nom: "Gants de protection - En plastique intérieur en tissus", categorieId: 7 },
{ nom: "Motopompe - Eagle à gazoil 150KVA", categorieId: 7 },
{ nom: "Grillage - Rouleau métallique de 25 m et une hauteur de 1,5m", categorieId: 7 },
{ nom: "Poteau - métallique de 2m", categorieId: 7 },
{ nom: "Tuyaux d'arrosages - Tube PVC de 75", categorieId: 7 },
{ nom: "Tuyaux d'arrosages - Tube gorgé de 75", categorieId: 7 },
{ nom: "Coude de 80 - PVC", categorieId: 7 },
{ nom: "Fil d'attache - Rouleau de fil métallique moux", categorieId: 7 },
{ nom: "Pulvérisateur de 16l - Pompe de type farmjet ou équivalent", categorieId: 7 },
{ nom: "Brouettes - De type hercule ou Euro ou équivalent", categorieId: 7 },
{ nom: "Pesticide en liquide de 250 ml - Caiman B19", categorieId: 7 },
{ nom: "Pesticide en liquide de 250 ml - Emapire", categorieId: 7 },
{ nom: "Pesticide bio - Limosin, Solsain, Piol, platsain, poudre de seem, HN", categorieId: 7 },
{ nom: "Compost /fumure organique - 5kg", categorieId: 7 },
{ nom: "Compost /fumure organique - 25kg", categorieId: 7 },
{ nom: "Compost /fumure organique - 50kg", categorieId: 7 },


      // Lot 8 : Semences
      { nom: "Semences variées", categorieId: 8 },
      { nom: "Semence de Piment Rouge - Variété Papri king / 80j / 5g", categorieId: 8 },
{ nom: "Semence de Piment Rouge - Variété Papri king / 80j / 10g", categorieId: 8 },
{ nom: "Semence de Piment Rouge - Variété Papri king / 80j / 50g", categorieId: 8 },
{ nom: "Semence de Piment Rouge - Variété Papri king / 80j / 100g", categorieId: 8 },
{ nom: "Semence de Piment Rouge - Variété Papri king / 80j / 500g", categorieId: 8 },
{ nom: "Semence de Piment Jaune - Variété Papri queen / 80j / 5g", categorieId: 8 },
{ nom: "Semence de Piment Jaune - Variété Papri queen / 80j / 10g", categorieId: 8 },
{ nom: "Semence de Piment Jaune - Variété Papri queen / 80j / 50g", categorieId: 8 },
{ nom: "Semence de Piment Jaune - Variété Papri queen / 80j / 100g", categorieId: 8 },
{ nom: "Semence de Piment Jaune - Variété Papri queen / 80j / 500g", categorieId: 8 },
{ nom: "Semence de Gombo Vert clair - Variété Keleya / 50-60j / 5g", categorieId: 8 },
{ nom: "Semence de Gombo Vert clair - Variété Keleya / 50-60j / 10g", categorieId: 8 },
{ nom: "Semence de Gombo Vert clair - Variété Keleya / 50-60j / 50g", categorieId: 8 },
{ nom: "Semence de Gombo Vert clair - Variété Keleya / 50-60j / 100g", categorieId: 8 },
{ nom: "Semence de Gombo Vert clair - Variété Keleya / 50-60j / 500g", categorieId: 8 },
{ nom: "Semence d'Aubergine Vert clair - Variété FBA 1 (Sissaga) / 90-100j / 5g", categorieId: 8 },
{ nom: "Semence d'Aubergine Vert clair - Variété FBA 1 (Sissaga) / 90-100j / 10g", categorieId: 8 },
{ nom: "Semence d'Aubergine Vert clair - Variété FBA 1 (Sissaga) / 90-100j / 50g", categorieId: 8 },
{ nom: "Semence d'Aubergine Vert clair - Variété FBA 1 (Sissaga) / 90-100j / 100g", categorieId: 8 },
{ nom: "Semence d'Aubergine Vert clair - Variété FBA 1 (Sissaga) / 90-100j / 500g", categorieId: 8 },
{ nom: "Semence de Tomate - Variété Petomech / 75j / 5g", categorieId: 8 },
{ nom: "Semence de Tomate - Variété Petomech / 75j / 10g", categorieId: 8 },
{ nom: "Semence de Tomate - Variété Petomech / 75j / 50g", categorieId: 8 },
{ nom: "Semence de Tomate - Variété Petomech / 75j / 100g", categorieId: 8 },
{ nom: "Semence de Tomate - Variété Petomech / 75j / 500g", categorieId: 8 },
{ nom: "Semence de Tomate - Variété Tropimech / 65-70j / 5g", categorieId: 8 },
{ nom: "Semence de Tomate - Variété Tropimech / 65-70j / 10g", categorieId: 8 },
{ nom: "Semence de Tomate - Variété Tropimech / 65-70j / 50g", categorieId: 8 },
{ nom: "Semence de Tomate - Variété Tropimech / 65-70j / 100g", categorieId: 8 },
{ nom: "Semence de Tomate - Variété Tropimech / 65-70j / 500g", categorieId: 8 },
{ nom: "Semence de Tomate - Variété Roma VF / 80-85j / 5g", categorieId: 8 },
{ nom: "Semence de Tomate - Variété Roma VF / 80-85j / 10g", categorieId: 8 },
{ nom: "Semence de Tomate - Variété Roma VF / 80-85j / 50g", categorieId: 8 },
{ nom: "Semence de Tomate - Variété Roma VF / 80-85j / 100g", categorieId: 8 },
{ nom: "Semence de Tomate - Variété Roma VF / 80-85j / 500g", categorieId: 8 },
{ nom: "Semence de Chou pommé - Variété KK Cross / 90-100j / 5g", categorieId: 8 },
{ nom: "Semence de Chou pommé - Variété KK Cross / 90-100j / 10g", categorieId: 8 },
{ nom: "Semence de Chou pommé - Variété KK Cross / 90-100j / 50g", categorieId: 8 },
{ nom: "Semence de Chou pommé - Variété KK Cross / 90-100j / 100g", categorieId: 8 },
{ nom: "Semence de Chou pommé - Variété KK Cross / 90-100j / 500g", categorieId: 8 },
{ nom: "Semence de Laitue Verte - Variété Batavia / 20-30j / 5g", categorieId: 8 },
{ nom: "Semence de Laitue Verte - Variété Batavia / 20-30j / 10g", categorieId: 8 },
{ nom: "Semence de Laitue Verte - Variété Batavia / 20-30j / 50g", categorieId: 8 },
{ nom: "Semence de Laitue Verte - Variété Batavia / 20-30j / 100g", categorieId: 8 },
{ nom: "Semence de Laitue Verte - Variété Batavia / 20-30j / 500g", categorieId: 8 },
{ nom: "Semence de Poivron Vert - Variété Coronado F1 / 60-65j / 5g", categorieId: 8 },
{ nom: "Semence de Poivron Vert - Variété Coronado F1 / 60-65j / 10g", categorieId: 8 },
{ nom: "Semence de Poivron Vert - Variété Coronado F1 / 60-65j / 50g", categorieId: 8 },
{ nom: "Semence de Poivron Vert - Variété Coronado F1 / 60-65j / 100g", categorieId: 8 },
{ nom: "Semence de Poivron Vert - Variété Coronado F1 / 60-65j / 500g", categorieId: 8 },
{ nom: "Semence de Concombre - Variété Nagano / 5g", categorieId: 8 },
{ nom: "Semence de Concombre - Variété Nagano / 10g", categorieId: 8 },
{ nom: "Semence de Concombre - Variété Nagano / 50g", categorieId: 8 },
{ nom: "Semence de Concombre - Variété Nagano / 100g", categorieId: 8 },
{ nom: "Semence de Concombre - Variété Nagano / 500g", categorieId: 8 },
{ nom: "Semence de Pastèque - Kaolac Technisem / 5g", categorieId: 8 },
{ nom: "Semence de Pastèque - Kaolac Technisem / 10g", categorieId: 8 },
{ nom: "Semence de Pastèque - Kaolac Technisem / 50g", categorieId: 8 },
{ nom: "Semence de Pastèque - Kaolac Technisem / 100g", categorieId: 8 },
{ nom: "Semence de Pastèque - Kaolac Technisem / 500g", categorieId: 8 },
{ nom: "Semence d'Epinard - Technisem / 5g", categorieId: 8 },
{ nom: "Semence d'Epinard - Technisem / 10g", categorieId: 8 },
{ nom: "Semence d'Epinard - Technisem / 50g", categorieId: 8 },
{ nom: "Semence d'Epinard - Technisem / 100g", categorieId: 8 },
{ nom: "Semence d'Epinard - Technisem / 500g", categorieId: 8 },
{ nom: "Semence de Carotte - New KARODA / 5g", categorieId: 8 },
{ nom: "Semence de Carotte - New KARODA / 10g", categorieId: 8 },
{ nom: "Semence de Carotte - New KARODA / 50g", categorieId: 8 },
{ nom: "Semence de Carotte - New KARODA / 100g", categorieId: 8 },
{ nom: "Semence de Carotte - New KARODA / 500g", categorieId: 8 },
{ nom: "Semence de Maïs - Variétés FBC 6 / 1kg", categorieId: 8 },
{ nom: "Semence de Maïs - Variétés Barka / 1kg", categorieId: 8 },
{ nom: "Semence de Maïs - Variétés Massongo / 1kg", categorieId: 8 },
{ nom: "Semence de Maïs - Variétés KPJ / 1kg", categorieId: 8 },
{ nom: "Semence de Maïs - Variétés KEJ / 1kg", categorieId: 8 },
{ nom: "Semence de Maïs - Variétés Espoir / 1kg", categorieId: 8 },
{ nom: "Semence de Maïs - Variétés Bondofa / 1kg", categorieId: 8 },
{ nom: "Semence de Sorgho - Variétés Sariasso / 1kg", categorieId: 8 },
{ nom: "Semence de Sorgho - Variétés Kpelga / 1kg", categorieId: 8 },
{ nom: "Semence de Sorgho - Variétés Grinkan / 1kg", categorieId: 8 },



      // Lot 9 : Kits Soudure
      { nom: "Kit soudure complet", categorieId: 9 },

      // Lot 10 : Kits Télécom
      { nom: "Cable chargeur (Type Android et Type-C)", categorieId: 10 },
      { nom: "Écouteur simple (avec fil)", categorieId: 10 },
      { nom: "Écouteur bluetooth (sans fil)", categorieId: 10 },
      { nom: "Foureaux smartphone", categorieId: 10 },
      { nom: "Téléphone incassable Tecno/Infinix", categorieId: 10 },
      { nom: "PowerBank 10 000mAh", categorieId: 10 },
      { nom: "PowerBank 20 000mAh", categorieId: 10 },
      { nom: "Chargeur universel de batterie (tas de 24)", categorieId: 10 },
      { nom: "Chargeur simple (sachet de 45)", categorieId: 10 },
      { nom: "Câble avec boitier", categorieId: 10 },
      { nom: "Batterie téléphone simple (1000 mAh)", categorieId: 10 },
      { nom: "Foureaux petit téléphone (plastique)", categorieId: 10 },
      { nom: "Téléphone en bouton (écran 1,52 pouce, batterie 1000mAh)", categorieId: 10 },
      { nom: "Carte mémoire 4GB", categorieId: 10 },
      { nom: "Colle pour plastification (1m)", categorieId: 10 },

      // Lot 11 : Mécanique
      { nom: "Pompe à vélo à main", categorieId: 11 },
      { nom: "Caisse à outils complet", categorieId: 11 },
      { nom: "Pneu de vélo (28 pouces ou 700mm)", categorieId: 11 },
      { nom: "Mojau à vélo (aluminium)", categorieId: 11 },
      { nom: "Chambre à air (28 pouces)", categorieId: 11 },
      { nom: "Jante (28 pouces)", categorieId: 11 },
      { nom: "Rayon (28 pouces)", categorieId: 11 },
      { nom: "Pièce à colle MF (paquet)", categorieId: 11 },
      { nom: "Dissolition (paquet)", categorieId: 11 },
      { nom: "Garre semi cuir (selle vélo)", categorieId: 11 },
      { nom: "Guidon vélo homme/femme", categorieId: 11 },
      { nom: "Caisse complète 182 outils mécanique auto/moto", categorieId: 11 },
      { nom: "Densimètre / pèse acide batterie", categorieId: 11 },
      { nom: "Sangle à cartouche métallique 500mm", categorieId: 11 },
      { nom: "Pied à coulisse 150mm", categorieId: 11 },
      { nom: "Parasolaire", categorieId: 11 },
      { nom: "Seringue à huile plastique 100ml", categorieId: 11 },

      // Lot 12 : Friperie
      { nom: "Ballot friperie homme (1er choix)", categorieId: 12 },
      { nom: "Ballot friperie femme (1er choix)", categorieId: 12 },
      { nom: "Ballot friperie enfant (1er choix)", categorieId: 12 }
    ];

    const tx = db.transaction("produits", "readwrite");
    const store = tx.objectStore("produits");

    produits.forEach(p => store.add(p));

    tx.oncomplete = () => console.log("✅ Lots 3 à 12 insérés !");
    tx.onerror = e => console.error("❌ Erreur insertion lots 3 à 12 :", e.target.error);
  };

  request.onerror = function(event) {
    console.error("Erreur ouverture DB :", event.target.error);
  };
})();
